title: Workbook
lang: en
description: Write an awesome description for your new site here

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   extension: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

#include:
#  - content
#  - content/geospatial
  
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
